# Homework 1

**Discipline:** Mathematics (Linear Algebra · Calculus · Probability & Statistics)

**Program:** M.S. in AI/ML Engineering — Neoversity

## Task 1: Image Matrices

Given the original image matrix $M$ and the effect matrix $E$:

$$M = \begin{pmatrix} 100 & 150 & 200 \\ 50 & 100 & 150 \\ 0 & 50 & 100 \end{pmatrix}, \quad E = \begin{pmatrix} 20 & 30 & 40 \\ 10 & 20 & 30 \\ 5 & 10 & 15 \end{pmatrix}$$

**1. Contrast adjustment ($0.5M$):** every element is multiplied by 0.5.

$$0.5M = \begin{pmatrix} 50 & 75 & 100 \\ 25 & 50 & 75 \\ 0 & 25 & 50 \end{pmatrix}$$

**2. Brightness correction ($M + 25$):** every element is increased by 25.

$$M+25 = \begin{pmatrix} 125 & 175 & 225 \\ 75 & 125 & 175 \\ 25 & 75 & 125 \end{pmatrix}$$

**3. Blending ($0.8M + 0.2E$):** weighted sum of the two matrices, e.g. for the top-left element:

$$0.8 \cdot 100 + 0.2 \cdot 20 = 84$$

$$0.8M+0.2E = \begin{pmatrix} 84 & 126 & 168 \\ 42 & 84 & 126 \\ 1 & 42 & 83 \end{pmatrix}$$

In [1]:
import numpy as np

M = np.array([[100, 150, 200],
              [50, 100, 150],
              [0, 50, 100]])

E = np.array([[20, 30, 40],
              [10, 20, 30],
              [5, 10, 15]])

# contrast adjustment
contrast = 0.5 * M

# brightness correction
brightness = M + 25

# blending
blended = 0.8 * M + 0.2 * E

print("Contrast (0.5 * M):\n", contrast.astype(int))
print("\nBrightness (M + 25):\n", brightness)
print("\nBlended (0.8*M + 0.2*E):\n", blended.astype(int))

Contrast (0.5 * M):
 [[ 50  75 100]
 [ 25  50  75]
 [  0  25  50]]

Brightness (M + 25):
 [[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

Blended (0.8*M + 0.2*E):
 [[ 84 126 168]
 [ 42  84 126]
 [  1  42  83]]


## Task 2: Movie Recommendation

User profile vector: $u = (8, 2, 5)$

**Step 1. Norm of the user vector:**

$$\|u\| = \sqrt{8^2+2^2+5^2} = \sqrt{93} \approx 9.644$$

**Step 2. Cosine similarity with each movie:**

Movie A, $v_A=(9,1,2)$:
$$u \cdot v_A = 84, \quad \|v_A\| = \sqrt{86} \approx 9.274, \quad \cos\theta_A \approx 0.939$$

Movie B, $v_B=(1,9,8)$:
$$u \cdot v_B = 66, \quad \|v_B\| = \sqrt{146} \approx 12.083, \quad \cos\theta_B \approx 0.566$$

Movie C, $v_C=(7,2,6)$:
$$u \cdot v_C = 90, \quad \|v_C\| = \sqrt{89} \approx 9.434, \quad \cos\theta_C \approx 0.989$$

**Conclusion:** Movie C (Drama) has the highest cosine similarity, so it best matches the user's profile.

In [2]:
import numpy as np

u = np.array([8, 2, 5])
v_A = np.array([9, 1, 2])
v_B = np.array([1, 9, 8])
v_C = np.array([7, 2, 6])

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

print(f"Norm of user vector ||u|| = {np.linalg.norm(u):.4f}\n")

movies = {"A (Action)": v_A, "B (Comedy)": v_B, "C (Drama)": v_C}

# similarity for each movie
for name, v in movies.items():
    print(f"Similarity with movie {name}: {cosine_similarity(u, v):.4f}")

best = max(movies, key=lambda name: cosine_similarity(u, movies[name]))
print(f"\nBest matching movie: {best}")

Norm of user vector ||u|| = 9.6437

Similarity with movie A (Action): 0.9393
Similarity with movie B (Comedy): 0.5664
Similarity with movie C (Drama): 0.9892

Best matching movie: C (Drama)


## Task 3: Production Analysis

System $Ax = b$:

$$\begin{pmatrix} 4 & 4 & 6 \\ 1 & 1 & 2 \\ 1 & 2 & 4 \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} = \begin{pmatrix} 460 \\ 130 \\ 240 \end{pmatrix}$$

**Step 1. Determinant:**

$$\det A = 4(1\cdot4-2\cdot2) - 4(1\cdot4-2\cdot1) + 6(1\cdot2-1\cdot1) = -2$$

Since $\det A \neq 0$, the system has a unique solution.

**Step 2. Solving the system.** From the second equation, $x_1 = 130 - x_2 - 2x_3$. Substituting into the first equation gives $x_3 = 30$. Substituting back into the third equation gives $x_2 = 50$, and finally $x_1 = 20$.

**Result:** $x_1=20$, $x_2=50$, $x_3=30$.

**Check:** $4(20)+4(50)+6(30)=460$, $20+50+60=130$, $20+100+120=240$ — matches $b$.

In [3]:
import numpy as np

A = np.array([[4, 4, 6],
              [1, 1, 2],
              [1, 2, 4]])

b = np.array([460, 130, 240])

# determinant check
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A:.2f}")

# solving Ax = b
x = np.linalg.solve(A, b)
print("Number of drones (Scout, Kamikaze, Cargo):", x)

# verification
print("\nCheck A @ x:", A @ x)
print("Original b:  ", b)

Determinant of A: -2.00
Number of drones (Scout, Kamikaze, Cargo): [20. 50. 30.]

Check A @ x: [460. 130. 240.]
Original b:   [460 130 240]


## Task 4: Trend Forecasting

Data: $t=[1,2,3,4,5]$, $y=[22,28,37,45,53]$

Design matrix:

$$A = \begin{pmatrix} 1 & 1 \\ 2 & 1 \\ 3 & 1 \\ 4 & 1 \\ 5 & 1 \end{pmatrix}$$

**Normal equations** $A^TAx = A^Ty$, $x=[k,b]^T$:

$$A^TA = \begin{pmatrix} 55 & 15 \\ 15 & 5 \end{pmatrix}, \quad A^Ty = \begin{pmatrix} 634 \\ 185 \end{pmatrix}$$

Solving:

$$55k+15b=634$$
$$15k+5b=185 \implies 3k+b=37$$

Substituting $b=37-3k$ into the first equation gives $10k=79$, so $k=7.9$ and $b=13.3$.

**Trend line:** $y = 7.9x + 13.3$

**Forecast for hour 6:**

$$\hat{y} = 7.9 \cdot 6 + 13.3 = 60.7$$

In [4]:
import numpy as np

t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])

# design matrix [t, 1]
A = np.vstack([t, np.ones(len(t))]).T

# least squares solution
k, b = np.linalg.lstsq(A, y, rcond=None)[0]
print(f"Trend line: y = {k:.2f}x + {b:.2f}")

# forecast for hour 6
y_pred = k * 6 + b
print(f"Predicted CPU load at hour 6: {y_pred:.2f}")

# normal equation, solved manually
ATA = A.T @ A
ATy = A.T @ y
k_manual, b_manual = np.linalg.solve(ATA, ATy)

print(f"\nManual normal equation: k = {k_manual:.2f}, b = {b_manual:.2f}")
print(f"lstsq result:           k = {k:.2f}, b = {b:.2f}")

Trend line: y = 7.90x + 13.30
Predicted CPU load at hour 6: 60.70

Manual normal equation: k = 7.90, b = 13.30
lstsq result:           k = 7.90, b = 13.30
